### ISSUE TITLE
Not all value types display correcty

### ISSUE THREAD

**Issue by ctrochalakis** [derailed/mongo3#2]
When showing collection documents the values are printed using the default #to_s method. When the values are arrays or hashes the output is unreadable.

Here is a quick fix for it using #inspect
http://github.com/ctrochalakis/mongo3/tree/pretty_values

**Comment by derailed** [comment]
Hi Christos,

   Did you update to 0.0.9 ? I had made a small change yesterday to better display hash and arrays... Still work in progress though and not ideal quiet yet....

Thanks!
Fernand

**Comment by ctrochalakis** [comment]
Hi Fernand,

For some reason I didn't noticed your changes... Works great, thanks :)

**Comment by derailed** [comment]
No worries ! Thanks for looking at it Christos.
