### ISSUE TITLE
Error running Mongo3

### ISSUE THREAD

**Issue by craigwblake** [derailed/mongo3#22]
I ran 'sudo gem install mongo3' and then ran 'mongo3' and I get this error:

NoMethodError - private method `public' called for Sinatra::Application:Class:
    /Library/Ruby/Gems/1.8/gems/mongo3-0.1.3/lib/helpers/main_helper.rb:21:in`v_styles'
    /Library/Ruby/Gems/1.8/gems/mongo3-0.1.3/lib/helpers/main_helper.rb:7:in `stylesheets'
    /Library/Ruby/Gems/1.8/gems/mongo3-0.1.3/lib/helpers/main_helper.rb:6:in`each'
    /Library/Ruby/Gems/1.8/gems/mongo3-0.1.3/lib/helpers/main_helper.rb:6:in `stylesheets'
    /Library/Ruby/Gems/1.8/gems/mongo3-0.1.3/bin/../lib/views/layout.erb:8:in`evaluate_source'
    /Library/Ruby/Gems/1.8/gems/tilt-1.3.3/lib/tilt/template.rb:144:in `cached_evaluate'
    /Library/Ruby/Gems/1.8/gems/tilt-1.3.3/lib/tilt/template.rb:127:in`evaluate'
    /Library/Ruby/Gems/1.8/gems/tilt-1.3.3/lib/tilt/template.rb:76:in `render'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb:636:in`render'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb:644:in `render'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb:644:in`catch'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb:644:in `render'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb:522:in`erb'
    /Library/Ruby/Gems/1.8/gems/mongo3-0.1.3/lib/controllers/explore.rb:29:in `GET /'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb:1211:in`call'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb:1211:in `compile!'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb:785:in`[]'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb:785:in `route!'
    /Library/Ruby/Gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb:801:in`route_eval'
.
.
.

**Comment by derailed** [comment]
Hi Craig,

```
I have updated the gem V 0.1.4. Should be much better now. Let me know if you're still having issues.
```

Thanks!
