### ISSUE TITLE
unable to find server

### ISSUE THREAD

**Issue by freegenie** [derailed/mongo3#3]
I get this error while accessing /collections/id: 

```
#<Mongo::OperationFailure: unauthorized>
NoMethodError - private method `split' called for nil:NilClass:
 /usr/bin/mongo3:19:in `load'
 /usr/bin/mongo3:19#<Rack::Session::Mongo:0x2b02c67519a0> is unable to find server.
```

**Comment by freegenie** [comment]
Ok, I found it's because the app is unable to connect to the specified mongo db to store session hash. I suppose it expects to receive an _open_ (no auth required) database as parameter.

**Comment by derailed** [comment]
Hi,
  Correct! mong3 uses mongo_rack session by default which expects a local instance running on the default port. This will only store mongo3 session info. You can change that by passing a --pool arg. See README for the settings.
