### ISSUE TITLE
Can't click on node images only on node label

### ISSUE THREAD

**Issue by a-musing-moose** [derailed/mongo3#4]
Hi Derailed,

Just trying out mongo3... awesome!

It did take me a while to work out how to browse to the individual databases within a node.  It seems that only the node names are clickable, not the nodes themselves. Is it possible to make the nodes clickable as well?

**Comment by derailed** [comment]
Ah. Thanks! I am sure there is. This is the default behavior with this particular js lib. 
I agree this isn't the most intuitive. If you want to take a crack at it, by all means, that will be a great contribution.
