### ISSUE TITLE
Cannot get mongo3 running

### ISSUE THREAD

**Issue by glappen** [derailed/mongo3#5]
Hello, trying to get mongo3 running on a server (is this supported, or should you run it on your local workstation only?).  Anyway, when I browse to the app, I get:

RuntimeError - Unable to grok yaml landscape file. syntax error on line 1, col 6: ` host:  int-mongodb-pch.staging.boost.pch.com':

Here is my landscape.yml file (I took out all the real hostnames, usernames, and password).

boost_staging:
    host:  int-mongodb-pch.staging.boost.pch.com
    user:  aaaaaaaa
    password: bbbbbbbbbb

boost_production:
    host: int-mongodb-pch.boost.pch.com
    user: bbbbbbbb
    password: aaaaaaaaa

What am I doing wrong?  Any help would be greatly appreciated!

**Comment by derailed** [comment]
Sure - you can run it either ways. It would be best to have a .ru file so you can run it on your server. Will put a sample one together. 
The configuration does look wrong. You need a proper yaml indent ie 2 spaces before each key/value pair of you env hash. Take a look a spec/configs for examples.

Thanks!

**Comment by glappen** [comment]
OK, I will try fixing that, I must have put tabs in by accident by editing the file on the server.

Also, I was thinking of running this under passenger instead of sinatra, would that work?.  Thanks!
