### ISSUE TITLE
Can't get it to compile in ubuntu 9.10

### ISSUE THREAD

**Issue by elpargo** [derailed/mongo3#6]
Hello,

I'm just trying this and I got the following error.

$ sudo gem install mongo3
Building native extensions.  This could take a while...
ERROR:  Error installing mongo3:
    ERROR: Failed to build gem native extension.

/usr/bin/ruby1.8 extconf.rb
extconf.rb:1:in `require': no such file to load -- mkmf (LoadError)
    from extconf.rb:1

Gem files will remain installed in /var/lib/gems/1.8/gems/mongo_ext-0.18.3 for inspection.
Results logged to /var/lib/gems/1.8/gems/mongo_ext-0.18.3/ext/cbson/gem_make.out

That is with 
$ gem1.8 --version
1.3.5

any pointers as to why the bson module failed?

**Comment by derailed** [comment]
Hi - looks like an issue with make. Do you have c++ and make installed on that box ?

-Fernand

**Comment by elpargo** [comment]
yea build-essential is installed.

$ which make gcc g++
/usr/bin/make
/usr/bin/gcc
/usr/bin/g++

**Comment by derailed** [comment]
Hum.. weird.. Does just typing make does anything? Do you have ruby-dev installed ?

**Comment by elpargo** [comment]
ahh ok ruby-dev got me over that step but now I see two problems.
1- the mongo3 is not installed properly 
2- when run manually i get http://paste.turbogears.org/paste/123109

**Comment by derailed** [comment]
Looks like I missed the json dependency. I'll update mongo3.  
For now
sudo gem install json

Also you should not need to unpack the gem. the mongo3 exec should be in /usr/bin
Not sure where it ends up on ubuntu as it depends on where your gems are installed.

**Comment by elpargo** [comment]
ok installed json and sinatra (also missing in the Rakefile)

That got it started but now I'm getting a 500 but that seems to be the missing config 
RuntimeError - Unable to grok yaml landscape file. No such file or directory
 with - - [05/Feb/2010:17:33:34 AST] "GET /explore HTTP/1.1" 500 30
- -> /explore

I though the new docs said it will try the default setup before using the file.

As for the unpack, I'm not sure what's up but the mongo3 executable is not installing properly.

**Comment by derailed** [comment]
Thanks! I'll update the dependencies on the next push.
Yes you must specify a landscape file before starting mongo3.

Thanks for reporting back!

**Comment by elpargo** [comment]
Awesome, Thanks for this great project and sorry for the newbiness. I'm not a ruby guy.

**Comment by derailed** [comment]
No worries - we are all newbies in various degrees... Thanks for the kind words!

**Comment by trbs** [comment]
@elpargo where did you find the bin/mongo3 file ?

**Comment by elpargo** [comment]
trbs ~/.gem/ruby/1.8/bin/mongo3

Sorry for the late reply :)
