### ISSUE TITLE
strange behavior with memcache

### ISSUE THREAD

**Issue by tcha-tcho** [derailed/mongo3#7]
hy derailed!! great work!! could you help-me? Are there a painless way to store this sessions? without external requirements... is that, just some users that gonna use the mongo3... How do we can run mongo3 as a daemon on the server without use passenger?

root@tests:~# mongo3 --pool "memcache://localhost:11211/mongo3"

!! Unexpected error while processing request: illegal character in key "BAh7CDoJbmFtZSILdGVzdGV4OgdpZG86FE1vbmdvOjpPYmplY3RJRAY6CkBk\nYXRhWxFpUGl7aV9pJ2kBtmkfaXJpKGlkaQBpAGkGOgtsb2NhbGUiB3B0\n--86339a26fa81e7e75d855aedb2c4ca86aa4e681b"

How do we insert the credentials for the inner dbs with auth?

Thanks in advance!

**Comment by derailed** [comment]
Hi -

  Thanks ! - Looks like the sessions are a bit confused. Have you tried clearing out your sessions?
  If mongo3 is to be shared I would really recommend running it with a web server. I'll push a sample rackup file on the next push to make that a bit easier. 
  Passing credential can be achieved using the landscape.yml file. Check out the docs for examples.

Thanks!

**Comment by derailed** [comment]
Looks like there might have been a bug in rack sessions - you might want to try rack 1.1.0
