### ISSUE TITLE
Clicking the logo sends you to http://localhost:6663/explore which 404s

### ISSUE THREAD

**Issue by elpargo** [derailed/mongo3#8]
That is all, I guess I should go to /

**Comment by derailed** [comment]
Hi 
   Thought I had fixed that... Which version are you running ?
    Thanks for reporting back!

**Comment by elpargo** [comment]
This is with mongo3-0.1.1 perhaps you have it in HEAD...

I really need to learn how to run things in ruby directly from a checkout in a virtualenv or whatever it is that you guys use :)

**Comment by derailed** [comment]
ok - you are right. that issue should now be fixed. 0.1.2

**Comment by elpargo** [comment]
Awesome. Thanks :)
